services:
  db:
    image: postgres:14-alpine
    container_name: examen-postgres
    environment:
      - POSTGRES_PASSWORD=temp2025
      - POSTGRES_DB=employee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: